# Define the landing page
"/": blogs

# Special behaviour
"calendars/(:num)/archive": controller=calendars&action=archive&id=$1
"calendars/(icalfeed|archive)": controller=calendars&action=$1
"galleries/(:num)/(createfile|updatefile|destroyfile|updatefilepositions)": controller=galleries&action=$2&id=$1
"language/(:alpha)": language=$1
"mails/(:num)/(create|resend)": controller=mails&action=$2&id=$1
"medias/(:any)/destroy": controller=medias&action=destroy&file=$1
"rss/(:alpha)(/(:num))?": controller=rss&section=$1&id=$3
"searches/(:any)": controller=searches&search=$1
"sessions/(password|verification|destroy)": controller=sessions&action=$1
"sites/(:alnum)": controller=sites&site=$1
"sitemap.xml": controller=sitemaps&type=xml&action=xml
"users/(:num)/token": controller=users&action=token&id=$1
"users/(:alnum)/verification": controller=users&action=verification&code=$1
"users/(:num)/(:alpha)": controller=users&action=$2&id=$1

# Shared behaviour
"(:alpha)/?": controller=$1&page=1
"(:alpha)/page/(:num)": controller=$1&page=$2
"(:alpha)/create": controller=$1&action=create
"(:alpha)/(:num)/(update|destroy|json|xml)": controller=$1&id=$2&action=$3
"(:alpha)/(:num)/(highlight|page)/(:any)": controller=$1&id=$2&$3=$4

# Magic rule
"(:alpha)/(:num)": controller=$1&id=$2&page=1
"(:alpha)/(:num).(xml|json)": controller=$1&id=$2&type=$3&page=1
"(:alpha)/(:num)/(:any)": controller=$1&id=$2&seo_title=$3&page=1
"(:alpha)/(:alpha).(xml|json)": controller=$1&action=$2&type=$3
"(:alpha).(xml|json)": controller=$1&type=$2

# Fixes
"blogs/(:any)/page/(:num)": controller=blogs&search=$1&page=$2
"blogs/(:any)": controller=blogs&search=$1