# Define the landing page
"/": blogs

# Special behaviour (Second blog RegEx is a temporary bugfix)
"blogs/(:any)/page/(:num)": controller=blogs&search=$1&page=$2
"blogs/(:num)(.(xml|json|rss|ajax))?": controller=blogs&id=$1&type=$3&page=1
"blogs/(:alnum(?<!create|update|destroy))(.(xml|json|rss|ajax))?": controller=blogs&search=$1&type=$3
"language/(:alpha)": language=$1
"medias/(:any)/destroy.(xml|json)": controller=medias&action=destroy&file=$1&type=$2
"auth/(:alpha)/(:any)" : controller=oauth&action=$1&response=$2
"sessions/auth/(:alpha)": controller=sessions&action=auth&type=$1
"searches/(:any)": controller=searches&search=$1
"sites/(:alnum)": controller=sites&site=$1
"sitemap.xml": controller=sitemaps&type=xml
"users/(:num)/token": controller=users&action=token&id=$1
"users/(:alnum)/verification": controller=users&action=verification&code=$1

# Shared behaviour
"(:alpha)/?": controller=$1&page=1
"(:alpha)/page/(:num)": controller=$1&page=$2
"(:alpha)/(:num)/(update|destroy)(.(json|xml))?": controller=$1&id=$2&action=$3&type=$5
"(:alpha)/(:num)/(highlight|page)/(:any)": controller=$1&id=$2&$3=$4
"(:alpha)/(:num)/(:alpha)(.(xml|json|rss|ajax))?": controller=$1&id=$2&action=$3&type=$5&page=1
"(:alpha)/(:num)(.(xml|json|rss|ajax))?": controller=$1&id=$2&type=$4&page=1
"(:alpha)/(:num)/(:any)": controller=$1&id=$2&seo_title=$3&page=1
"(:alpha)/(:alpha)(.(xml|json|rss|ajax))?": controller=$1&action=$2&type=$4
"(:alpha).(xml|json|rss|ajax)": controller=$1&type=$2